version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: nest-auth-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_pass
      POSTGRES_DB: nest_auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
